// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOWganuG2xMHA7bJAc_jk57j0WYhnw34U',
    appId: '1:436839965700:web:93d575eb511b2105fa0151',
    messagingSenderId: '436839965700',
    projectId: 'aplikasikesehatan-7ce04',
    authDomain: 'aplikasikesehatan-7ce04.firebaseapp.com',
    storageBucket: 'aplikasikesehatan-7ce04.appspot.com',
    measurementId: 'G-WKDC1V32R6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaKEDgGEfGUzr3DlAZWrrTYe7bPwFuWWA',
    appId: '1:436839965700:android:38309f34be596032fa0151',
    messagingSenderId: '436839965700',
    projectId: 'aplikasikesehatan-7ce04',
    storageBucket: 'aplikasikesehatan-7ce04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcK6ZZbOaWF5uDahg03up4VVEm4Skx3Tg',
    appId: '1:436839965700:ios:51d4b6e01c5fc440fa0151',
    messagingSenderId: '436839965700',
    projectId: 'aplikasikesehatan-7ce04',
    storageBucket: 'aplikasikesehatan-7ce04.appspot.com',
    iosClientId: '436839965700-47s30rrlrmge2cpujearpm4230c97peo.apps.googleusercontent.com',
    iosBundleId: 'com.example.tugasakhirAplikasiKesehatan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcK6ZZbOaWF5uDahg03up4VVEm4Skx3Tg',
    appId: '1:436839965700:ios:51d4b6e01c5fc440fa0151',
    messagingSenderId: '436839965700',
    projectId: 'aplikasikesehatan-7ce04',
    storageBucket: 'aplikasikesehatan-7ce04.appspot.com',
    iosClientId: '436839965700-47s30rrlrmge2cpujearpm4230c97peo.apps.googleusercontent.com',
    iosBundleId: 'com.example.tugasakhirAplikasiKesehatan',
  );
}
